export const paths = {
    home: '/',
    search: '/search',
    trades: '/trades',
    trade: '/trade',
    news: '/news',
    account: '/account',
    networkSettings: '/network-settings',
    receive: '/receive',
    exchange: '/exchange',
    exchangeSuccess: '/exchange-success',
    send: '/send',
    sell: '/sell',
    sendSuccess: '/send-success',
    seedphrase: '/seedphrase',
    userProfile: '/user-profile',
    userSubscribeSuccess: '/subscribe-success',
    users: '/users',
    newUsers: '/new-users',
}
